# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=255, unique=True, verbose_name='商品コード')),
                ('item_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.PositiveIntegerField(verbose_name='価格')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'item',
            },
        ),
    ]
